import {
    mobile,
    backend,
    creator,
    gmail,
    downloads,
    printer,
    medical,
    celebrating,
    Hepa,
    Gast,
    Color,
    Hepat,
    Gener,
    Inte,
    Med,
    consalt,
    diag,
    office,
    Inter,
    crowd,
    akn,
    dhan,
    diagn,
    cons,
    pakages,
    AmarlabLogo,
    purehealth,
    hajj,
    home,
    about,
    branch,
    contact,
    telephone,
    customer,
    doctor,
    freelance,
    login,
    messages,
    signup,
    web,
    javascript,
    typescript,
    html,
    css,
    reactjs,
    redux,
    tailwind,
    nodejs,
    mongodb,
    git,
    figma,
    docker,
    meta,
    starbucks,
    tesla,
    shopify,
    carrent,
    jobit,
    tripguide,
    threejs,
    Badda,
    Barishal,
    BoguraU1,
    BoguraU2,
    BoguraU3,
    Chattogram,
    Dhanmondi,
    Dinajpur,
    EnglishRoad,
    Gazipur,
    Jatrabari,
    Khulna,
    Kushtia,
    MirpurU1,
    MirpurU2,
    Mymensingh,
    Narayangonj,
    Noakhali,
    Rajshahi,
    RangpurU1,
    RangpurU2,
    Savar,
    ShantinagarU1,
    ShantinagarU2,
    ShyamoliU1,
    ShyamoliU2,
    UttaraGaribENewaz,
    UttaraU1,
    UttaraU2,
    AchintoKumarNag,
    AjoyKumarDatta,
    MdSohelChowdhury,
    MdFoyzurRahman,
    MdJahurulIslamRony,
    MdMahbuburRahmanChowdhury,
    MdMizanurRahmanBiswas,
    MdMosharrofHossain,
    MdShahidulIslam,
    MdShahiMahmud,
    MrAbdullahAlMahmud,
    MrFaridMohammadShamim,
    MrFirozMia,
    MrMdAbdulAhad,
    MrMuhammadReazHossain,
    MrNezamulHaqueRipon,
    MrNurIslam,
    MrOalyAshrafKhan,
    MrRajuAhmmedKhalek,
    MrRezwanAhmed,
    MrZohurulIslam,
    ShamsuzzohaKhanJohn,
    AbdurRazzak,
    AfzalHossain,
    DrMostafizurRahman,
    LateTaheraAkhter,
    MdAlauddinFCMA,
    MdSahabUddin,
    MdZiaulHaqueFaruk,
    MohammadArif,
    MosaddequeHossain,
    MostafaNurmohammadPalash,
    MrKabirAhmed,
    SardinRahman,
  } from "../assets";


  const doctorData = {
    branches: [
      {
        braID: 1,
        braName: "Dhanmondi",
        specilizations: [
          {
            SpecilizationID: 1,
            specializationName: "Cardiology",
            doctorDetails: [
              {
                drGender: "Male",
                drName: "Prof. Dr. M. Nazrul Islam",
                degree: "MBBS, FCPS, FRCP (Edin), FCCP, FACC, FESC. BSMMU (PG)",
                weekday: [
                  {
                    day: "Saturday",
                    time: "3:00 PM - 5:00 PM",
                  },
                  {
                    day: "Sunday",
                    time: "3:00 PM - 5:00 PM",
                  },
                  {
                    day: "Monday",
                    time: "3:00 PM - 5:00 PM",
                  },
                  {
                    day: "Tuesday",
                    time: "3:00 PM - 5:00 PM",
                  },
                  {
                    day: "Wednesday",
                    time: "3:00 PM - 5:00 PM",
                  },
                  {
                    day: "Thursday",
                    time: "3:00 PM - 5:00 PM",
                  },
                ],
                building: "Bhaban-1",
                room: "401",
                drNumber: 1711563450,
                email: "mnislam3512@gmail.com",
                newPatient: "2000",
                oldPatient: "2000",
                report: "Free",
                assistantName: "Anis",
                assistantGender: "Male",
                ext: "111421",
                assistantMobile: "01768431923",
                image: "Yes",
              },
              // More doctorDetails under Cardiology...
            ],
          },
          {
            SpecilizationID: 2,
            specializationName: "Medicine",
            doctorDetails: [
              {
                drGender: "Male",
                drName: "Prof. Dr. M.A Azhar",
                degree:
                  "MBBS, FCPS (Medicine), FACP, FRCP (Edin). Sir Salimullah Medical College & Mitford Hospital, Dhaka.",
                weekday: [
                  {
                    day: "Saturday",
                    time: "10:00 AM - 5:00 PM",
                  },
                  {
                    day: "Sunday",
                    time: "10:00 AM - 5:00 PM",
                  },
                  {
                    day: "Monday",
                    time: "10:00 AM - 5:00 PM",
                  },
                  {
                    day: "Tuesday",
                    time: "10:00 AM - 5:00 PM",
                  },
                  {
                    day: "Wednesday",
                    time: "10:00 AM - 5:00 PM",
                  },
                  {
                    day: "Thursday",
                    time: "10:00 AM - 5:00 PM",
                  },
                ],
                building: "Bhaban-2",
                room: "304",
                drNumber: 1711364552,
                email: "",
                newPatient: "1000",
                oldPatient: "500",
                report: "Free",
                assistantName: "Chan Miah",
                assistantGender: "Male",
                ext: "2249",
                assistantMobile: "01736131369",
                image: "No",
              },
              // More doctorDetails under Medicine...
            ],
          },
          // More specializations in Dhanmondi...
        ],
      },
      {
        braID: 2,
        braName: "English Road",
        specilizations: [
          {
            SpecilizationID: 1,
            specializationName: "Cardiology",
            doctorDetails: [
              {
                drGender: "Male",
                drName: "Prof. Dr. M. Nazrul Islam",
                degree: "MBBS, FCPS, FRCP (Edin), FCCP, FACC, FESC. BSMMU (PG)",
                weekday: [
                  {
                    day: "Saturday",
                    time: "3:00 PM - 5:00 PM",
                  },
                  {
                    day: "Sunday",
                    time: "3:00 PM - 5:00 PM",
                  },
                  {
                    day: "Monday",
                    time: "3:00 PM - 5:00 PM",
                  },
                  {
                    day: "Tuesday",
                    time: "3:00 PM - 5:00 PM",
                  },
                  {
                    day: "Wednesday",
                    time: "3:00 PM - 5:00 PM",
                  },
                  {
                    day: "Thursday",
                    time: "3:00 PM - 5:00 PM",
                  },
                ],
                building: "Bhaban-1",
                room: "401",
                drNumber: 1711563450,
                email: "mnislam3512@gmail.com",
                newPatient: "2000",
                oldPatient: "2000",
                report: "Free",
                assistantName: "Anis",
                assistantGender: "Male",
                ext: "111421",
                assistantMobile: "01768431923",
                image: "Yes",
              },
              // More doctorDetails under Cardiology...
            ],
          },
          {
            SpecilizationID: 2,
            specializationName: "Medicine",
            doctorDetails: [
              {
                drGender: "Male",
                drName: "Prof. Dr. M.A Azhar",
                degree:
                  "MBBS, FCPS (Medicine), FACP, FRCP (Edin). Sir Salimullah Medical College & Mitford Hospital, Dhaka.",
                weekday: [
                  {
                    day: "Saturday",
                    time: "10:00 AM - 5:00 PM",
                  },
                  {
                    day: "Sunday",
                    time: "10:00 AM - 5:00 PM",
                  },
                  {
                    day: "Monday",
                    time: "10:00 AM - 5:00 PM",
                  },
                  {
                    day: "Tuesday",
                    time: "10:00 AM - 5:00 PM",
                  },
                  {
                    day: "Wednesday",
                    time: "10:00 AM - 5:00 PM",
                  },
                  {
                    day: "Thursday",
                    time: "10:00 AM - 5:00 PM",
                  },
                ],
                building: "Bhaban-2",
                room: "304",
                drNumber: 1711364552,
                email: "",
                newPatient: "1000",
                oldPatient: "500",
                report: "Free",
                assistantName: "Chan Miah",
                assistantGender: "Male",
                ext: "2249",
                assistantMobile: "01736131369",
                image: "No",
              },
              // More doctorDetails under Medicine...
            ],
          },
          // More specializations in English Road...
        ],
      },
      // More branches...
    ],
  };

  export {
    
    doctorData
  };