import {
    mobile,
    backend,
    creator,
    gmail,
    downloads,
    printer,
    medical,
    celebrating,
    Hepa,
    Gast,
    Color,
    Hepat,
    Gener,
    Inte,
    Med,
    consalt,
    diag,
    office,
    Inter,
    crowd,
    akn,
    dhan,
    diagn,
    cons,
    pakages,
    AmarlabLogo,
    purehealth,
    hajj,
    home,
    about,
    branch,
    contact,
    telephone,
    customer,
    doctor,
    freelance,
    login,
    messages,
    signup,
    web,
    javascript,
    typescript,
    html,
    css,
    reactjs,
    redux,
    tailwind,
    nodejs,
    mongodb,
    git,
    figma,
    docker,
    meta,
    starbucks,
    tesla,
    shopify,
    carrent,
    jobit,
    tripguide,
    threejs,
    Badda,
    Barishal,
    BoguraU1,
    BoguraU2,
    BoguraU3,
    Chattogram,
    Dhanmondi,
    Dinajpur,
    EnglishRoad,
    Gazipur,
    Jatrabari,
    Khulna,
    Kushtia,
    MirpurU1,
    MirpurU2,
    Mymensingh,
    Narayangonj,
    Noakhali,
    Rajshahi,
    RangpurU1,
    RangpurU2,
    Savar,
    ShantinagarU1,
    ShantinagarU2,
    ShyamoliU1,
    ShyamoliU2,
    UttaraGaribENewaz,
    UttaraU1,
    UttaraU2,
    AchintoKumarNag,
    AjoyKumarDatta,
    MdSohelChowdhury,
    MdFoyzurRahman,
    MdJahurulIslamRony,
    MdMahbuburRahmanChowdhury,
    MdMizanurRahmanBiswas,
    MdMosharrofHossain,
    MdShahidulIslam,
    MdShahiMahmud,
    MrAbdullahAlMahmud,
    MrFaridMohammadShamim,
    MrFirozMia,
    MrMdAbdulAhad,
    MrMuhammadReazHossain,
    MrNezamulHaqueRipon,
    MrNurIslam,
    MrOalyAshrafKhan,
    MrRajuAhmmedKhalek,
    MrRezwanAhmed,
    MrZohurulIslam,
    ShamsuzzohaKhanJohn,
    AbdurRazzak,
    AfzalHossain,
    DrMostafizurRahman,
    LateTaheraAkhter,
    MdAlauddinFCMA,
    MdSahabUddin,
    MdZiaulHaqueFaruk,
    MohammadArif,
    MosaddequeHossain,
    MostafaNurmohammadPalash,
    MrKabirAhmed,
    SardinRahman,
  } from "../assets";

  const projects1 = [
    {
      branchID: 1,
      heading: "Dhanmondi",
      image: Dhanmondi,
      name: "Popular Diagnostic Centre Ltd. (Dhanmondi)",
      address: "House # 16, Road # 2, Dhanmondi, Dhaka1205",
      Hotline: "10636, 09666 787801 ",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3652.2197080792394!2d90.37959757619976!3d23.73954337867781!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755b8ca7af5f82b%3A0xce7d1ab6b16a027!2sPopular%20Diagnostic%20Centre%20Ltd.!5e0!3m2!1sen!2sbd!4v1706512680599!5m2!1sen!2sbd",
        reportDownload: "http://119.40.80.131/",
        braManImg: AchintoKumarNag,
        braManName: "Achinto Kumar Nag",
        braManDesignation: "AGM (HR & Admin)",
      },
    },
    {
      branchID: 2,
      heading: "English Road",
      image: EnglishRoad,
      name: "Popular Diagnostic Centre Ltd. (English road)",
      address: "House # 2, English Road, Dhaka.",
      Hotline: "09666 787802",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=23.713776,90.4109699&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MdMahbuburRahmanChowdhury,
        braManName: "Md. Mahbubur Rahman Chowdhury",
        braManDesignation: "Branch Manager",
      },
    },
    {
      branchID: 3,
      heading: "Shantinagar (U-1)",
      image: ShantinagarU1,
      name: "Popular Diagnostic Centre Ltd. (Shantinagar (U-1))",
      address: "House # 11, Shantinagar , Motijheel, Dhaka.",
      Hotline: "09666 787803",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=23.7412031,90.4124384&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MdShahiMahmud,
        braManName: "Md. Shahi Mahmud",
        braManDesignation: "AGM & Head of Branch",
      },
    },
    {
      branchID: 4,
      heading: "Shantinagar (U-2)",
      image: ShantinagarU2,
      name: "Popular Diagnostic Centre Ltd. (Shantinagar (U-2))",
      address: "Level - 4, Building # 15, Shantinagar, Motijheel, Dhaka.",
      Hotline: "09666 787803",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=23.7420844,90.4121534&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MdShahiMahmud,
        braManName: "Md. Shahi Mahmud",
        braManDesignation: "AGM & Head of Branch",
      },
    },
    {
      branchID: 5,
      heading: "Shyamoli (U-1)",
      image: ShyamoliU1,
      name: "Popular Diagnostic Centre Ltd. (Shyamoli (U-1))",
      address:
        "22/7 A S M Nuruzzaman Road, Block-B, Babor Road, Mohammadpur, Dhaka-1207.",
      Hotline: "09666 787806",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=23.7718253,90.3674465&hl=es;z=14&output=embed",
        reportDownload:
          "http://prosoft.populardiagnostic.com:8877/ords/f?p=700:3:8271679877280:::::",
        braManImg: MrNezamulHaqueRipon,
        braManName: "Mr. Nezamul Haque Ripon",
        braManDesignation: "AGM & Head of Branch",
      },
    },
    {
      branchID: 6,
      heading: "Shyamoli (U-2)",
      image: ShyamoliU2,
      name: "Popular Diagnostic Centre Ltd. (Shyamoli (U-2))",
      address:
        "House: 1/5, Block- B, Mohammadpur Housing State, Gajnabi Road, Mohammadpur",
      Hotline: "09666-787806",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=23.76892267744971,90.36856338476504&hl=es;z=14&output=embed",
        reportDownload:
          "http://prosoft.populardiagnostic.com:8877/ords/f?p=700:3:8271679877280:::::",
        braManImg: MrNezamulHaqueRipon,
        braManName: "Mr. Nezamul Haque Ripon",
        braManDesignation: "AGM & Head of Branch",
      },
    },
    {
      branchID: 7,
      heading: "Mirpur (U-1)",
      image: MirpurU1,
      name: "Popular Diagnostic Centre Ltd. (Mirpur (U-1))",
      address:
        "House # 67, Avenue # 5, Block # C, Section-6 Mirpur, (Original-10),Pallabi, Dhaka.",
      Hotline: "09666 787807",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=23.8106471,90.3673446&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MrAbdullahAlMahmud,
        braManName: "Mr. Abdullah Al Mahmud",
        braManDesignation: "AGM & Head of Branch",
      },
    },
    {
      branchID: 8,
      heading: "Mirpur (U-2)",
      image: MirpurU2,
      name: "Popular Diagnostic Centre Ltd. (Mirpur (U-2))",
      address:
        "House # 02, Avenue # 01, Block # A, Section-10(Bnaroshi Polli Gate-01), Pallabi, Mirpur, Dhaka.",
      Hotline: "09666 787807",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=24.7433735,90.4059255&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MrAbdullahAlMahmud,
        braManName: "Mr. Abdullah Al Mahmud",
        braManDesignation: "AGM & Head of Branch",
      },
    },
    {
      branchID: 9,
      heading: "Badda",
      image: Badda,
      name: "Popular Diagnostic Centre Ltd. (Badda)",
      address: "Cha-90/2, North Badda (Pragoti Sharoni), Dhaka-1212.",
      Hotline: "09666 787809",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=23.7885462,90.4250215&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MrFirozMia,
        braManName: "Mr. Firoz Mia",
        braManDesignation: "Head of Branch",
      },
    },
    {
      branchID: 10,
      heading: "Uttara (U-1)",
      image: UttaraU1,
      name: "Popular Diagnostic Centre Ltd. (Uttara (U-1))",
      address:
        "House # 21, Road # 7, Sector # 4, Jashim Uddin More, Uttara, Dhaka-1230",
      Hotline: "09666 787805",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=23.8610668,90.40031&hl=es;z=14&output=embed",
        reportDownload:
          "http://prosoft.populardiagnostic.com:8877/ords/f?p=700:3:8271679877280:::::",
        braManImg: MrZohurulIslam,
        braManName: "Mr. Zohurul Islam",
        braManDesignation: "Senior Branch Manager",
      },
    },
    {
      branchID: 11,
      heading: "Uttara (U-2)",
      image: UttaraU2,
      name: "Popular Diagnostic Centre Ltd. (Uttara (U-2))",
      address:
        "House # 25, Road # 7, Sector # 4, Jashim Uddin Moar, Uttara, Dhaka.",
      Hotline: "09666 787805",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=23.8613902,90.4007901&hl=es;z=14&output=embed",
        reportDownload:
          "http://prosoft.populardiagnostic.com:8877/ords/f?p=700:3:8271679877280:::::",
        braManImg: MrZohurulIslam,
        braManName: "Mr. Zohurul Islam",
        braManDesignation: "Senior Branch Manager",
      },
    },
    {
      branchID: 12,
      heading: "Uttara Garib E Newaz",
      image: UttaraGaribENewaz,
      name: "Popular Diagnostic Centre Ltd. (Uttara Garib-E-Newaz)",
      address:
        "House #41, Uttara-Garib-E-Newaz Avenue, Sector # 13, Uttara, Dhaka",
      Hotline: "09666787823",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=23.87267692544794,90.3906825609275&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MdJahurulIslamRony,
        braManName: " Md. Jahurul Islam Rony",
        braManDesignation: "Branch In-Charge",
      },
    },
    {
      branchID: 13,
      heading: "Jatrabari",
      image: Jatrabari,
      name: "Popular Diagnostic Centre Ltd. (Jatrabari)",
      address: "33,Shahid Faruk sarak, North jatrabari, Dhaka-1204",
      Hotline: "09666787822",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=23.709443131735878,90.43211759426138&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MdMizanurRahmanBiswas,
        braManName: " Md. Mizanur Rahman Biswas",
        braManDesignation: "Branch Manager",
      },
    },
    {
      branchID: 14,
      heading: "Savar",
      image: Savar,
      name: "Popular Diagnostic Centre Ltd. (Savar)",
      address: "E/22, Talbagh, Anandapur, Savar, Dhaka.",
      Hotline: "09666 787808",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=23.839972,90.257242&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MrRajuAhmmedKhalek,
        braManName: " Mr. Raju Ahmmed Khalek",
        braManDesignation: "Branch In-Charge",
      },
    },
    {
      branchID: 15,
      heading: "Gazipur",
      image: Gazipur,
      name: "Popular Diagnostic Centre Ltd. (Gazipur)",
      address:
        "Gazipur Shibbari More (Near VIP Bus Terminal and Walton Show Room)",
      Hotline: "09666 787816",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=23.9969328,90.4148069&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: AjoyKumarDatta,
        braManName: "Ajoy Kumar Datta",
        braManDesignation: "Branch Manager",
      },
    },
    {
      branchID: 16,
      heading: "Narayangonj",
      image: Narayangonj,
      name: "Popular Diagnostic Centre Ltd. (Narayangonj)",
      address: "231/4, Bangabandhu Road, Balur Math, Chashara, Narayangonj.",
      Hotline: "09666 787804",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dhaka",
        location:
          "https://maps.google.com/maps?q=23.6223054,90.5004152&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MdShahidulIslam,
        braManName: "Md. Shahidul Islam",
        braManDesignation: "AGM & Head of Branch",
      },
    },
    {
      branchID: 17,
      heading: "Bogura (U-1)",
      image: BoguraU1,
      name: "Popular Diagnostic Centre Ltd. (Bogura (U-1))",
      address: "H # 12/305, Thanthania Bus-Stand Sherpur Road, Bogura.",
      Hotline: "09666 787812",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Bogura",
        location:
          "https://maps.google.com/maps?q=24.8321186,89.3762719&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MrRezwanAhmed,
        braManName: "Mr. Rezwan Ahmed",
        braManDesignation: "Senior Branch Manager",
      },
    },
    {
      branchID: 18,
      heading: "Bogura (U-2)",
      image: BoguraU2,
      name: "Popular Diagnostic Centre Ltd. (Bogura (U-2))",
      address: "H # 12/310, Thanthania Bus-Stand Sherpur Road, Bogura.",
      Hotline: "09666 787812",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Bogura",
        location:
          "https://maps.google.com/maps?q=24.8321186,89.3762719&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MrRezwanAhmed,
        braManName: "Mr. Rezwan Ahmed",
        braManDesignation: "Senior Branch Manager",
      },
    },
    {
      branchID: 19,
      heading: "Bogura (U-3)",
      image: BoguraU3,
      name: "Popular Diagnostic Centre Ltd. (Bogura (U-3))",
      address: "H # 14/1979, Rahman Market, Silimpur, Bogra.",
      Hotline: "09666 787812",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Bogura",
        location:
          "https://maps.google.com/maps?q=24.8280095,89.3527289&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MrRezwanAhmed,
        braManName: "Mr. Rezwan Ahmed",
        braManDesignation: "Senior Branch Manager",
      },
    },
    {
      branchID: 20,
      heading: "Rajshahi",
      image: Rajshahi,
      name: "Popular Diagnostic Centre Ltd. (Rajshahi)",
      address: "House # 474, Chowdhury Tower, Laxmipur, Rajshahi.",
      Hotline: "09666 787811",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Rajshahi",
        location:
          "https://maps.google.com/maps?q=24.3723311,88.5811372&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MrFaridMohammadShamim,
        braManName: "Mr. Farid Mohammad Shamim",
        braManDesignation: "AGM & Head of Branch",
      },
    },
    {
      branchID: 21,
      heading: "Noakhali",
      image: Noakhali,
      name: "Popular Diagnostic Centre Ltd. (Noakhali)",
      address:
        "House #1222, New Bus stand (Near Shaheed Bhulu Stadium) Maijdee Court, Noakhali.",
      Hotline: "09666 787818",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Noakhali",
        location:
          "https://maps.google.com/maps?q=22.875063,91.097225&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MrMuhammadReazHossain,
        braManName: "Mr. Muhammad Reaz Hossain",
        braManDesignation: "Branch Manager",
      },
    },
    {
      branchID: 22,
      heading: "Chattogram",
      image: Chattogram,
      name: "Popular Diagnostic Centre Ltd. (Chattogram)",
      address: "20/B. K. B. Fazlul Kader Road, Panchlaish, Chattogram.",
      Hotline: "09666 787810",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Chattogram",
        location:
          "https://maps.google.com/maps?q=22.360777,91.831786&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MrOalyAshrafKhan,
        braManName: "Mr. Oaly Ashraf Khan",
        braManDesignation: "Senior Branch Manager",
      },
    },
    {
      branchID: 23,
      heading: "Mymensingh",
      image: Mymensingh,
      name: "Popular Diagnostic Centre Ltd. (Mymensingh)",
      address:
        "252/1, Charpara Road (Opposite of Mymensingh Medical College & Hospital), Mymensingh.",
      Hotline: "09666 787814",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Mymensingh",
        location:
          "https://maps.google.com/maps?q=24.744623,90.408583&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MrNurIslam,
        braManName: "Mr. Nur Islam",
        braManDesignation: "Senior Branch Manager",
      },
    },
    {
      branchID: 24,
      heading: "Rangpur (U-1)",
      image: RangpurU1,
      name: "Popular Diagnostic Centre Ltd. (Rangpur (U-1))",
      address: "77/1, Road No-1, Dhap, Jail Road, Rangpur.",
      Hotline: "09666 787813",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Rangpur",
        location:
          "https://maps.google.com/maps?q=25.7610566,89.2348999&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MrMdAbdulAhad,
        braManName: "Mr. Md. Abdul Ahad",
        braManDesignation: "Branch Manager",
      },
    },
    {
      branchID: 25,
      heading: "Rangpur (U-2)",
      image: RangpurU2,
      name: "Popular Diagnostic Centre Ltd. (Rangpur (U-2))",
      address: "77/1, Road No-1, Dhap, Jail Road, Rangpur.",
      Hotline: "09666 787813",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Rangpur",
        location:
          "https://maps.google.com/maps?q=25.7610566,89.2348999&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MrMdAbdulAhad,
        braManName: "Mr. Md. Abdul Ahad",
        braManDesignation: "Branch Manager",
      },
    },
    {
      branchID: 26,
      heading: "Dinajpur",
      image: Dinajpur,
      name: "Popular Diagnostic Centre Ltd. (Dinajpur)",
      address: "House #44, 1 No. Upashahar, Fulbari Bus stand, Dinajpur.",
      Hotline: "09666 787815",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Dinajpur",
        location:
          "https://maps.google.com/maps?q=25.6199955,88.6449272&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MdFoyzurRahman,
        braManName: "Md. Foyzur Rahman",
        braManDesignation: "Branch Manager",
      },
    },
    {
      branchID: 27,
      heading: "Khulna",
      image: Khulna,
      name: "Popular Diagnostic Centre Ltd. (Khulna)",
      address:
        "Popular  Diagnostic  Centre Ltd. Khulna Branch, 37 KDA Avenue, Khulna.",
      Hotline: "09666 787821",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Khulna",
        location:
          "https://maps.google.com/maps?q=22.815210,89.555067&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MdSohelChowdhury,
        braManName: "Md. Sohel Chowdhury",
        braManDesignation: "Branch Manager",
      },
    },
    {
      branchID: 28,
      heading: "Kushtia",
      image: Kushtia,
      name: "Popular Diagnostic Centre Ltd. (Kushtia)",
      address:
        "City Tower - House No.1, Mir Mosharraf Hossain Road, Coart Para, Kushtia",
      Hotline: "09666 787817",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Kushtia",
        location:
          "https://maps.google.com/maps?q=23.903603,89.127746&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: ShamsuzzohaKhanJohn,
        braManName: "Shamsuzzoha Khan John",
        braManDesignation: "Branch In Charge",
      },
    },
    {
      branchID: 29,
      heading: "Barishal",
      image: Barishal,
      name: "Popular Diagnostic Centre Ltd. (Barishal)",
      address:
        "109, 955 Shahid Nazrul Islam Sarak, South Alekanda Banglabazar, Barishal.",
      Hotline: "09666 787819",
      Email: "info@populardiagnostic.com",
      branchPage: {
        braCity: "Barishal",
        location:
          "https://maps.google.com/maps?q=22.692741,90.361966&hl=es;z=14&output=embed",
        reportDownload: "http://119.40.80.131/",
        braManImg: MdMosharrofHossain,
        braManName: "Md. Mosharrof Hossain",
        braManDesignation: "Branch Manager",
      },
    },
  ];


  export {
    
    projects1
   
  };