import {
    mobile,
    backend,
    creator,
    gmail,
    downloads,
    printer,
    medical,
    celebrating,
    Hepa,
    Gast,
    Color,
    Hepat,
    Gener,
    Inte,
    Med,
    consalt,
    diag,
    office,
    Inter,
    crowd,
    akn,
    dhan,
    diagn,
    cons,
    pakages,
    AmarlabLogo,
    purehealth,
    hajj,
    home,
    about,
    branch,
    contact,
    telephone,
    customer,
    doctor,
    freelance,
    login,
    messages,
    signup,
    web,
    javascript,
    typescript,
    html,
    css,
    reactjs,
    redux,
    tailwind,
    nodejs,
    mongodb,
    git,
    figma,
    docker,
    meta,
    starbucks,
    tesla,
    shopify,
    carrent,
    jobit,
    tripguide,
    threejs,
    Badda,
    Barishal,
    BoguraU1,
    BoguraU2,
    BoguraU3,
    Chattogram,
    Dhanmondi,
    Dinajpur,
    EnglishRoad,
    Gazipur,
    Jatrabari,
    Khulna,
    Kushtia,
    MirpurU1,
    MirpurU2,
    Mymensingh,
    Narayangonj,
    Noakhali,
    Rajshahi,
    RangpurU1,
    RangpurU2,
    Savar,
    ShantinagarU1,
    ShantinagarU2,
    ShyamoliU1,
    ShyamoliU2,
    UttaraGaribENewaz,
    UttaraU1,
    UttaraU2,
    AchintoKumarNag,
    AjoyKumarDatta,
    MdSohelChowdhury,
    MdFoyzurRahman,
    MdJahurulIslamRony,
    MdMahbuburRahmanChowdhury,
    MdMizanurRahmanBiswas,
    MdMosharrofHossain,
    MdShahidulIslam,
    MdShahiMahmud,
    MrAbdullahAlMahmud,
    MrFaridMohammadShamim,
    MrFirozMia,
    MrMdAbdulAhad,
    MrMuhammadReazHossain,
    MrNezamulHaqueRipon,
    MrNurIslam,
    MrOalyAshrafKhan,
    MrRajuAhmmedKhalek,
    MrRezwanAhmed,
    MrZohurulIslam,
    ShamsuzzohaKhanJohn,
    AbdurRazzak,
    AfzalHossain,
    DrMostafizurRahman,
    LateTaheraAkhter,
    MdAlauddinFCMA,
    MdSahabUddin,
    MdZiaulHaqueFaruk,
    MohammadArif,
    MosaddequeHossain,
    MostafaNurmohammadPalash,
    MrKabirAhmed,
    SardinRahman,
  } from "../assets";

  const projects = [
    {
      id: 1,
      name: "HEALTH DIAGNOSIS",
      description:
        "Ambulance BD 24 is the best ambulance service in Dhaka, Bangladesh. We provide emergency ambulance service in Dhaka city and transport patient.",
      tags: [
        {
          name: "Indhaka",
          color: "blue-text-gradient",
        },
        {
          name: "Outsidedhaka",
          color: "green-text-gradient",
        },
      ],
      video: diagn,
      source_code_link: "http://populardiagnostic.com/",
    },
    {
      id: 2,
      name: "HEALTH CONSULTATION",
      description:
        "Blood Bank Management System (BBMS) under Safe Blood Transfusion Program, HSM, DGHS. Blood Transfusion Transfusion Program, HSM, DGHS.",
      tags: [
        {
          name: "Indhaka",
          color: "blue-text-gradient",
        },
        {
          name: "Outsidedhaka",
          color: "green-text-gradient",
        },
      ],
      video: cons,
      source_code_link: "http://populardiagnostic.com/",
    },
    {
      id: 3,
      name: "HEALTH PAKAGES",
      description:
        "We believe everyone should have access to convenient and quality healthcare. Our health checks and packages help you stay on top of your.",
      tags: [
        {
          name: "Indhaka",
          color: "blue-text-gradient",
        },
        {
          name: "Outsidedhaka",
          color: "green-text-gradient",
        },
      ],
      video: pakages,
      source_code_link: "http://populardiagnostic.com/",
    },
  ];

  export {
   
    projects
    
  };