import {
    mobile,
    backend,
    creator,
    gmail,
    downloads,
    printer,
    medical,
    celebrating,
    Hepa,
    Gast,
    Color,
    Hepat,
    Gener,
    Inte,
    Med,
    consalt,
    diag,
    office,
    Inter,
    crowd,
    akn,
    dhan,
    diagn,
    cons,
    pakages,
    AmarlabLogo,
    purehealth,
    hajj,
    home,
    about,
    branch,
    contact,
    telephone,
    customer,
    doctor,
    freelance,
    login,
    messages,
    signup,
    web,
    javascript,
    typescript,
    html,
    css,
    reactjs,
    redux,
    tailwind,
    nodejs,
    mongodb,
    git,
    figma,
    docker,
    meta,
    starbucks,
    tesla,
    shopify,
    carrent,
    jobit,
    tripguide,
    threejs,
    Badda,
    Barishal,
    BoguraU1,
    BoguraU2,
    BoguraU3,
    Chattogram,
    Dhanmondi,
    Dinajpur,
    EnglishRoad,
    Gazipur,
    Jatrabari,
    Khulna,
    Kushtia,
    MirpurU1,
    MirpurU2,
    Mymensingh,
    Narayangonj,
    Noakhali,
    Rajshahi,
    RangpurU1,
    RangpurU2,
    Savar,
    ShantinagarU1,
    ShantinagarU2,
    ShyamoliU1,
    ShyamoliU2,
    UttaraGaribENewaz,
    UttaraU1,
    UttaraU2,
    AchintoKumarNag,
    AjoyKumarDatta,
    MdSohelChowdhury,
    MdFoyzurRahman,
    MdJahurulIslamRony,
    MdMahbuburRahmanChowdhury,
    MdMizanurRahmanBiswas,
    MdMosharrofHossain,
    MdShahidulIslam,
    MdShahiMahmud,
    MrAbdullahAlMahmud,
    MrFaridMohammadShamim,
    MrFirozMia,
    MrMdAbdulAhad,
    MrMuhammadReazHossain,
    MrNezamulHaqueRipon,
    MrNurIslam,
    MrOalyAshrafKhan,
    MrRajuAhmmedKhalek,
    MrRezwanAhmed,
    MrZohurulIslam,
    ShamsuzzohaKhanJohn,
    AbdurRazzak,
    AfzalHossain,
    DrMostafizurRahman,
    LateTaheraAkhter,
    MdAlauddinFCMA,
    MdSahabUddin,
    MdZiaulHaqueFaruk,
    MohammadArif,
    MosaddequeHossain,
    MostafaNurmohammadPalash,
    MrKabirAhmed,
    SardinRahman,
  } from "../assets";


  const testimonials = [
    {
      testimonial:
        "A complete, advanced and friendly diagnostic and medical services provider in Bangladesh. Their qualified workforce and quality equipment give best result for any treatment like an international service.",
      name: "Mr. Ahmed",
      designation: "CFO",
      company: "Biman Bangladesh",
      image:
        "http://populardiagnostic.com/public/testimonial/1-20190319155227.jpg",
    },
    {
      testimonial:
        "Popular Diagnostic Centre Ltd. provides best diagnostic and medical services. They have most advanced medical equipment to diagnosis any type of diseases. I am so satisfied for their customer support.",
      name: "Mr. Hasan",
      designation: "Chairperson",
      company: "Brac Bank",
      image:
        "http://populardiagnostic.com/public/testimonial/2-20190319153146.jpg",
    },
  ];

  export {
    
    testimonials,
   
  };