import {
    mobile,
    backend,
    creator,
    gmail,
    downloads,
    printer,
    medical,
    celebrating,
    Hepa,
    Gast,
    Color,
    Hepat,
    Gener,
    Inte,
    Med,
    consalt,
    diag,
    office,
    Inter,
    crowd,
    akn,
    dhan,
    diagn,
    cons,
    pakages,
    AmarlabLogo,
    purehealth,
    hajj,
    home,
    about,
    branch,
    contact,
    telephone,
    customer,
    doctor,
    freelance,
    login,
    messages,
    signup,
    web,
    javascript,
    typescript,
    html,
    css,
    reactjs,
    redux,
    tailwind,
    nodejs,
    mongodb,
    git,
    figma,
    docker,
    meta,
    starbucks,
    tesla,
    shopify,
    carrent,
    jobit,
    tripguide,
    threejs,
    Badda,
    Barishal,
    BoguraU1,
    BoguraU2,
    BoguraU3,
    Chattogram,
    Dhanmondi,
    Dinajpur,
    EnglishRoad,
    Gazipur,
    Jatrabari,
    Khulna,
    Kushtia,
    MirpurU1,
    MirpurU2,
    Mymensingh,
    Narayangonj,
    Noakhali,
    Rajshahi,
    RangpurU1,
    RangpurU2,
    Savar,
    ShantinagarU1,
    ShantinagarU2,
    ShyamoliU1,
    ShyamoliU2,
    UttaraGaribENewaz,
    UttaraU1,
    UttaraU2,
    AchintoKumarNag,
    AjoyKumarDatta,
    MdSohelChowdhury,
    MdFoyzurRahman,
    MdJahurulIslamRony,
    MdMahbuburRahmanChowdhury,
    MdMizanurRahmanBiswas,
    MdMosharrofHossain,
    MdShahidulIslam,
    MdShahiMahmud,
    MrAbdullahAlMahmud,
    MrFaridMohammadShamim,
    MrFirozMia,
    MrMdAbdulAhad,
    MrMuhammadReazHossain,
    MrNezamulHaqueRipon,
    MrNurIslam,
    MrOalyAshrafKhan,
    MrRajuAhmmedKhalek,
    MrRezwanAhmed,
    MrZohurulIslam,
    ShamsuzzohaKhanJohn,
    AbdurRazzak,
    AfzalHossain,
    DrMostafizurRahman,
    LateTaheraAkhter,
    MdAlauddinFCMA,
    MdSahabUddin,
    MdZiaulHaqueFaruk,
    MohammadArif,
    MosaddequeHossain,
    MostafaNurmohammadPalash,
    MrKabirAhmed,
    SardinRahman,
  } from "../assets";


  const topManagement = [
    {
      manID: 1,
      manImg: LateTaheraAkhter,
      manName: "Late Tahera Akhter",
      manDesignation: "Chairman",
    },
    {
      manID: 2,
      manImg: DrMostafizurRahman,
      manName: "Dr. Mostafizur Rahman",
      manDesignation: "Managing Director",
    },
    {
      manID: 3,
      manImg: SardinRahman,
      manName: "Sardin Rahman",
      manDesignation: "Deputy Managing Director",
    },
    {
      manID: 4,
      manImg: AfzalHossain,
      manName: "Afzal Hossain",
      manDesignation: "Advisor, Marketing",
    },
    {
      manID: 5,
      manImg: MosaddequeHossain,
      manName: "Mosaddeque Hossain",
      manDesignation: "General Manager, Customer Services",
    },
    {
      manID: 6,
      manImg: MdAlauddinFCMA,
      manName: "Md Alauddin, FCMA",
      manDesignation: "DGM & Head of Finance & Accounts",
    },
    {
      manID: 7,
      manImg: AchintoKumarNag,
      manName: "Achinto Kumar Nag",
      manDesignation: "AGM (HR & Admin)",
    },
    {
      manID: 8,
      manImg: MostafaNurmohammadPalash,
      manName: "Mostafa Nurmohammad (Palash)",
      manDesignation: "AGM, (Engineering)",
    },
    {
      manID: 9,
      manImg: AbdurRazzak,
      manName: "Abdur Razzak",
      manDesignation: "AGM, (Finance & Accounts)",
    },
    {
      manID: 10,
      manImg: MohammadArif,
      manName: "Mohammad Arif",
      manDesignation: "Manager, (ICT)",
    },
    {
      manID: 11,
      manImg: MdZiaulHaqueFaruk,
      manName: "Md Ziaul Haque Faruk",
      manDesignation: "Manager, (Marketing)",
    },
    {
      manID: 12,
      manImg: MrKabirAhmed,
      manName: "Mr Kabir Ahmed",
      manDesignation: "Manager, (Engineering)",
    },
    {
      manID: 13,
      manImg: MdSahabUddin,
      manName: "Md Sahab Uddin",
      manDesignation: "Manager, (Finance & Accounts)",
    },
  ];

  export {
   
    topManagement,
   
  };